- name: install nginx repository
  template: src=nginx.repo dest=/etc/yum.repos.d/nginx.repo mode=0644

- name: install nginx
  yum: name=nginx state=latest enablerepo=nginx

- name: copy nginx configuration
  template: src=nginx.conf dest=/etc/nginx/nginx.conf mode=0644
  notify: restart nginx

- name: copy nginx default configuration
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf mode=0644
  notify: restart nginx

- name: nginx ssl directory
  file: path=/etc/nginx/ssl state=directory owner=root group=root mode=0755

- name: copy nginx ssl pem
  template: src=nginx.pem dest=/etc/nginx/ssl/nginx.pem mode=0644
  notify: restart nginx

- name: copy nginx ssl key
  template: src=nginx.key dest=/etc/nginx/ssl/nginx.key mode=0644
  notify: restart nginx

- name: automatic load when boot
  command: systemctl enable nginx.service

- name: start nginx
  command: systemctl start nginx.service
